#!/usr/bin/env python3
"""Render and verify committed global instruction entrypoints."""

from __future__ import annotations

import argparse
import difflib
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_SOURCE = REPO_ROOT / "agent-instructions" / "shared.md"
CODEX_SOURCE = REPO_ROOT / "agent-instructions" / "codex.md"
CODEX_OUTPUT = REPO_ROOT / "codex" / "AGENTS.md"
CLAUDE_SHARED_OUTPUT = REPO_ROOT / "claude" / "shared-agent-policy.md"

CODEX_HEADER = """<!--
Generated by scripts/render-agent-instructions.py from:
- agent-instructions/shared.md
- agent-instructions/codex.md

Do not edit this file directly. Edit the source fragments and rerun the renderer.
-->
# Dave's Global Agent Instructions

"""

CLAUDE_SHARED_HEADER = """<!--
Generated by scripts/render-agent-instructions.py from agent-instructions/shared.md.
Do not edit this file directly. Edit the source and rerun the renderer.
-->
"""


def normalize(text: str) -> str:
    """Normalize source text to UTF-8-compatible LF content."""
    return text.replace("\r\n", "\n").replace("\r", "\n").strip()


def render_outputs(shared: str, codex: str) -> dict[Path, bytes]:
    """Return exact UTF-8 bytes for every committed generated entrypoint."""
    shared = normalize(shared)
    codex = normalize(codex)
    return {
        CODEX_OUTPUT: (CODEX_HEADER + shared + "\n\n" + codex + "\n").encode("utf-8"),
        CLAUDE_SHARED_OUTPUT: (CLAUDE_SHARED_HEADER + shared + "\n").encode("utf-8"),
    }


def working_tree_outputs() -> dict[Path, bytes]:
    """Render expected outputs from working-tree source files."""
    shared = SHARED_SOURCE.read_bytes().decode("utf-8")
    codex = CODEX_SOURCE.read_bytes().decode("utf-8")
    return render_outputs(shared, codex)


def display_path(path: Path) -> str:
    """Return a concise repository-relative path when possible."""
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def index_blob(path: Path) -> bytes:
    """Read a repository path exactly as staged in Git's index."""
    relative = display_path(path)
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "show", f":{relative}"],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        detail = result.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(f"cannot read staged {relative}: {detail}")
    return result.stdout


def index_outputs() -> tuple[dict[Path, bytes], dict[Path, bytes]]:
    """Return expected and actual generated outputs from the staged snapshot."""
    shared = index_blob(SHARED_SOURCE).decode("utf-8")
    codex = index_blob(CODEX_SOURCE).decode("utf-8")
    expected = render_outputs(shared, codex)
    actual = {path: index_blob(path) for path in expected}
    return expected, actual


def report_mismatch(path: Path, actual: bytes, expected: bytes) -> None:
    """Print a readable text diff, including byte-only mismatch notice."""
    label = display_path(path)
    actual_text = actual.decode("utf-8", errors="replace")
    expected_text = expected.decode("utf-8", errors="replace")
    diff = list(
        difflib.unified_diff(
            actual_text.splitlines(),
            expected_text.splitlines(),
            fromfile=label,
            tofile="rendered sources",
            lineterm="",
        )
    )
    for line in diff:
        print(line)
    if not diff:
        print("byte mismatch: line endings or encoding differ")


def check_outputs(expected: dict[Path, bytes], actual: dict[Path, bytes]) -> int:
    """Return zero when every actual output matches expected bytes."""
    stale = False
    for path, expected_bytes in expected.items():
        actual_bytes = actual.get(path, b"")
        label = display_path(path)
        if actual_bytes == expected_bytes:
            print(f"current: {label}")
            continue
        stale = True
        print(f"stale: {label}")
        report_mismatch(path, actual_bytes, expected_bytes)
    return 1 if stale else 0


def check_working_tree() -> int:
    """Verify generated working-tree files byte-for-byte."""
    expected = working_tree_outputs()
    actual = {path: path.read_bytes() if path.exists() else b"" for path in expected}
    return check_outputs(expected, actual)


def check_index() -> int:
    """Verify generated files against source blobs staged in Git's index."""
    try:
        expected, actual = index_outputs()
    except (RuntimeError, UnicodeDecodeError) as exc:
        print(f"staged agent-instruction check failed: {exc}")
        return 1
    return check_outputs(expected, actual)


def write_outputs() -> None:
    """Write every generated output using deterministic UTF-8 LF bytes."""
    for path, content in working_tree_outputs().items():
        path.write_bytes(content)
        print(f"rendered: {display_path(path)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="verify working-tree outputs without writing",
    )
    mode.add_argument(
        "--check-index",
        action="store_true",
        help="verify generated files against the staged Git snapshot",
    )
    args = parser.parse_args()

    if args.check:
        return check_working_tree()
    if args.check_index:
        return check_index()
    write_outputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
